### ISSUE TITLE
Database Implementation

### ISSUE THREAD

**Issue by Azurethi** [Collective-SB/ISAN#17]
Database module needs to be implemented

**Comment by CalenLoki** [comment]
It looks like nobody made the database module/addon yet.
So here's what I just wrote.
https://docs.google.com/document/d/1B1hfB5GaqrUeizMl4uqbZUuU2g0A22ea-b9RMLkZJyM/edit
It's made for ISAN v1 with WNS, but should be easy to convert to any other.

**Comment by Azurethi** [comment]
> It looks like nobody made the database module/addon yet.
> So here's what I just wrote.
> https://docs.google.com/document/d/1B1hfB5GaqrUeizMl4uqbZUuU2g0A22ea-b9RMLkZJyM/edit
> It's made for ISAN v1 with WNS, but should be easy to convert to any other.

This is a cool feature @CalenLoki, however it's not what the core DB is for (this core modules is for storing data about dev transmitters, as we cant edit their message to include an ISAN lighthouse header).

@MrChip2k is just adding his own implementation of a waypoint manager for V2. You're welcome to submit a PR of your own as a separate addon in the same way, or more ideally we try to get the two of you working together to merge the best features of both.
