### ISSUE TITLE
BUG: Autopilot v4 lines length wrong

### ISSUE THREAD

**Issue by th3fallen** [Collective-SB/ISAN#40]
**Describe the bug**
Coping https://github.com/Collective-SB/ISAN/blob/master/src/addons/Autopilot/Auto%20v4.yolol into a yolo script lines 17 and 18 are over the line length

**To Reproduce**
1. Go to https://github.com/Collective-SB/ISAN/blob/master/src/addons/Autopilot/Auto%20v4.yolol
2. Copy the source to your yolo chip
3. When you get to line 17 and 8 you'll see they're too long

**Expected behavior**
source to fit on chip

**Comment by Azurethi** [comment]
This was outdated in-dev code. closing
