### ISSUE TITLE
BUG: Speed reporting in SSD test mode is inconsistent

### ISSUE THREAD

**Issue by TheFallenTwo** [Collective-SB/ISAN#41]
**Describe the bug**
In the space ship designer the speed reported by ISAN is inconsistent, varying greatly depending on the heading. Head straight forward or backward will report my ships is going about 60 m/s, going up or down will report 80 m/s, and going left or right will report 150 m/s. ISAN quad in use.

**To Reproduce**
1. Go to the space ship designer and load up a ship with ISAN on an advanced chip and so set to 0
2. Enter test mode and fly forward, allowing it to reach it's top speed and make note of the speed
3. Turn 90° tot he right and allow the ship to reach it's full speed and make another note of it
4. The speeds should be different. If not, it may only occur if you have a fast ship

**Expected behavior**
The speeds should be consistent and a fairly accurate estimate of the ship's speed, similar to how it would be reported outside of the test mode.

**Comment by Azurethi** [comment]
Significant changes have been made to the speed calculation section of Isan as of v2.5. Cannot reproduce this bug, so assuming I've fixed it in the process. Let me know if you run into any issues with the latest version
