### ISSUE TITLE
BUG: v2.5: Enable external XX,YY and ZZ variables causes script to stay at line 18

### ISSUE THREAD

**Issue by r-diggz** [Collective-SB/ISAN#46]
**Describe the bug**
When trying to enable the XX, YY and ZZ external variables per the installation documentation on page 9, the script always stops at line 18 saying to disable speed on a basic chip. This script is running on an advanced chip.

Here are what lines 14, 15 and 16 look before enabling external variables:
```
x+=(6-x)*(x<7) xx=(t+i)/e+g/u-f/k yy=i/l-t/mm+(g+f)/nn zz=(g+f-t-i)/o
st=:_==c :_=rr+h+xm+xx/n*A+ym+yy/n*A+zm+zz/n*A+sm+s gotoej+x*so+p*st
w+=xx uu+=yy vv+=zz r=w-tu j=uu-uv v=vv-vt ej+=(ii++%3)>1 gotox
```

Here is after:
```
x+=(6-x)*(x<7):xx=(t+i)/e+g/u-f/k :yy=i/l-t/mm+(g+f)/nn:zz=(g+f-t-i)/o
st=:_==c :_=rr+h+xm+:xx/n*A+ym+:yy/n*A+zm+:zz/n*A+sm+sGOTOej+x*so+p*st
w+=:xx uu+=:yy vv+=:zz r=w-tu j=uu-uv v=vv-vt ej+=(ii++%3)>1 gotox
```

I had to remove some of the spaces on lines 14 and 15 to stay under the 70 character cap. 

**To Reproduce**
1. Follow the installation guide for 'Q' deployment on an Advanced yolol chip.
2. Update lines 14, 15 and 16 per page 9 of the installation guide to enable external variables for xx, yy and zz.
3. Script will flow to line 18 and stay there until you remove the use of external.
4. profit... kinda

**Expected behavior**
The variables for XX, YY and ZZ should be stored on yolol memory chip.

**Screenshots**

**Additional context**
The script has no issues working when leaving the xx, yy and zz variables internal to the script.
I have tried setting the po=1 and 0 with no change.
I have enabled and disabled speed with no change. 
I have verified the receivers are configured with A:AT, B:BT, C:CT and D:DT. (Using capital letters)
I have verified the all yolol chips and memory cards are on the same network.
Maybe im just being stupid with how im removing spaces... im not sure.

**Comment by Azurethi** [comment]
The modules section of [the pdf](https://isan.to/isan.pdf) was updated when 2.5 was released. There's no longer space for the double char global vars as you've noticed yourself
