### ISSUE TITLE
ISAN 2.5 goes directly into OFFLINE

### ISSUE THREAD

**Issue by Cabu** [Collective-SB/ISAN#47]
To stop that I needed to replace the line 15 by:
```
st=:_!=c :_=rr+h+xm+xx/n*A+ym+yy/n*A+zm+zz/n*A+sm+s goto(ej+x*so)*st
```

**Comment by Azurethi** [comment]
I expect you've made some other mistake when copying the code into the game. Your replacement for line 15 just removes the ability to shut the system down. Please look for help in the isan_tech_support channel of the collective discord before posting issues here.
