### ISSUE TITLE
BUG: Quad ISAN not working, reverting to Mono & all receiver fields are changed to copy receiver "A" after going into test mode

### ISSUE THREAD

**Issue by bghyt** [Collective-SB/ISAN#48]
**Describe the bug**
every receiver's being set to "A" out of A,B,C,D & reporting mono not quad ISAN

**To Reproduce**
Steps to reproduce the behaviour:
1. add receivers & name them as per https://isan.to/isan.pdf#page=7
2. install yolol onto a adv chip
3. go into test mode
4. all receiver fields where C,CT,B,BT,D,DT should be are now reset to A&AT respectivly

**Expected behaviour**
Quad ISAN with co-ordinates and speed

**Screenshots**
https://cdn.discordapp.com/attachments/671016420238426142/888076700133515294/unknown.png

**Additional context**
i also tried ISAN 2.5.2 but it was also seemingly broken, i put the ISAN on it's own network but i had the same issue, i have also tried removing all other yolol chips from my build, and a "hacky" method where you remove the A,B,C,D,AT,BT,CT,DT fields, i tried also rebooting ISAN but to no avail it seems to not work at all when i put it into the yolol socket

**Comment by Azurethi** [comment]
Likely a connection issue specific to your install rather than a bug, reach out on discord for help
