### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by usurpine** [Collective-SB/ISAN#49]
**Describe the bug**
Pos: Z: has a factor of 10 against my old ISAN

**To Reproduce**
1. Install Isan2 to a Ship with old ISAN
2. Compar x: y: and z:
3. fly around and stop the ship and wait until all values stop moving
4. x, y are same but z is exactly 10x bigger

**Expected behavior**
Value z should be z/10

**Screenshots**

**Additional context**
<img width="255" alt="isan2" src="https://user-images.githubusercontent.com/75980532/134003020-e5fd90d7-0b1e-4432-b067-a5e36e51503e.png">

**Comment by usurpine** [comment]
I am not sura about if the old Isan was wrong or the new Isan, but anyway if you communicate with people still having old Isan installed and there are a lot of ships out there who are using the old Isan, they will never meet up at the same positions.

**Comment by Azurethi** [comment]
Can you add screenshots of the code in both chips?

**Comment by usurpine** [comment]
We have dived the zz with 10 to fix the problem. But to do that there is not enough place in line 14, so we move the zz calculation down and added the /10
<img width="935" alt="isan2fix" src="https://user-images.githubusercontent.com/75980532/134088130-66026182-b29f-4e57-93b8-2bf5caf14158.png">

**Comment by usurpine** [comment]
not nice, but it will generate now good results.

**Comment by usurpine** [comment]
<img width="1199" alt="Isan1_some_code_by_Duke" src="https://user-images.githubusercontent.com/75980532/134088657-941f344a-eef8-4bae-a96e-8b6fcee0e05c.png">
This is my old isan i had on my ship.

**Comment by Azurethi** [comment]
That's not quite isan, it's some code I threw together for duke a while ago. I must've made a mistake in there, the newest one is tested to work. You should remove the div 10
