### ISSUE TITLE
Can we have a radar/display script to show if one is on the right course to target?

### ISSUE THREAD

**Issue by Bluelight82** [Collective-SB/ISAN#54]
Can we have a radar/display script for ISAN2.5 to show if one is on the right course to target?

Any chance you guys know of a Yolol script for something like a radar or target display for ISAN2.5 Navigation Bundle? 
I only have alignment% and it's not very helpful. 

A full autopilot suite would also be nice if it does not exist yet?

**Comment by Azurethi** [comment]
See Firestar99's Compass & FixerID's Autopilot here: https://github.com/Thaccus/Starbase-Nav-Suite

ISAN X also has a full waypoint ap, demo'd here: https://www.youtube.com/watch?v=CNsu2DJGKtU

Unfortunately SB's devs have yet to address the limitations of transmitters/receivers or improve sensors to make these very worthwhile
